version: "3.7"

services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: usuario_prueba
      POSTGRES_PASSWORD: pass_prueba
      PGDATA: /var/lib/postgresql/data
    volumes:
    - db-data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: usuario_prueba
      PGADMIN_DEFAULT_PASSWORD: pass_prueba
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "8080:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    links:
    - "db:pgsql-server"
volumes:
  db-data:
  pgadmin-data: